[toolchain]
channel = "stable"
components = ["rust-src", "rust-std", "rustfmt", "clippy", "llvm-tools-preview"]
targets = [
    "x86_64-pc-windows-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin"
]
